version: '3'
services:
  web:
    build: api
    ports:
     - "8000:8000"
    volumes:
     - ./api:/usr/src/app
     - /usr/src/app/node_modules
    links:
      - db
  db:
    image: influxdb
    ports:
     - "8086:8086"