version: '3'
services:
  web:
    build: api
    ports:
     - "8000:8000"
    volumes:
     - ./api:/usr/src/app
     - /usr/src/app/node_modules
    links:
      - db
  db:
    image: influxdb
    volumes:
     - /var/lib/influxdb 
    # ports:
    #  - "8086:8086"
  processing:
    build: flask
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
    links:
      - web
  fe:
    build: frontend
    ports:
     - "3000:3000"
    volumes:
     - ./frontend:/usr/src/app
     - /usr/src/app/node_modules
    links:
      - web
  reverseproxy:
    build: reverseproxy
    ports:
      - 80:80
    restart: always